/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unam.app;

import com.mysql.cj.jdbc.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisj
 */
public class VentasIndex extends javax.swing.JFrame {
    Connection con=unam.conexcion.getConection();
    private float costo;
    private int idmodelo;
    private int numero;
    private int cantidad;
    private String tipo;
    private String color;
    private String marca;
    private String clasificacion;
    float total;
    /**
     * Creates new form VentasIndex
     */
            
    public VentasIndex() throws SQLException {
        initComponents();
        cargarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_modelo = new javax.swing.JTable();
        btn_Comprar = new javax.swing.JButton();
        cantidad_tt = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnRegreso = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_modelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_modeloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_modelo);

        btn_Comprar.setText("Comprar");
        btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComprarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        btnRegreso.setText("Salir");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Comprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegreso))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Comprar)
                    .addComponent(cantidad_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComprarActionPerformed
        java.util.Date javaDate= new Date();
        Date date= new java.sql.Date(javaDate.getYear(),javaDate.getMonth(),
                javaDate.getDay());
        String nombre = JOptionPane.showInputDialog(null, "Inserta Nombre");
        int opcion = JOptionPane.showConfirmDialog(null, "Confirmar compra:\n\n\t"
                + "Modelo: "+getIdmodelo()+"\n\tMarca: "+getMarca()+
                "\n\tCosto: "+total*(int)cantidad_tt.getValue()+
                "\n\tFecha: "+ date);
        //0. si 1. no 3.cancelar
        switch(opcion){
            
            case 0: 
                CallableStatement calls;    
                try {
                    PreparedStatement ps;
                    ps= con.prepareStatement("START TRANSACTION");
                    ps.execute();
                    calls = (CallableStatement) con.prepareCall("CALL venta_acto(?,?,?,?,?)");
                    calls.setString(1,  ""+getIdmodelo());
                    calls.setString(2, ""+date);
                    calls.setString (3, ""+total*(int)cantidad_tt.getValue());
                    calls.setString(4,nombre);
                    calls.setInt(5,(int)cantidad_tt.getValue());
                    calls.execute();
                    ps= con.prepareStatement("COMMIT");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Compra Realizada");
                    cargarTabla();
                } catch (SQLException ex) {
                    Logger.getLogger(VentasIndex.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_btn_ComprarActionPerformed
    
    private void tb_modeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_modeloMouseClicked
        try {
            PreparedStatement ps;
            ResultSet rs;
            int Fila = tb_modelo.getSelectedRow();
            String codigo = tb_modelo.getValueAt(Fila, 0).toString();
            ps = con.prepareStatement("SELECT idmodelo,marca,costo "
                    + "FROM modelotro WHERE idmodelo=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();
            
            while (rs.next()) {
                setIdmodelo(rs.getInt("idmodelo"));
                setMarca(rs.getString("marca"));
                total=rs.getFloat("costo");
                
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tb_modeloMouseClicked

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresoActionPerformed
    public void cargarTabla() throws SQLException{
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            tb_modelo.setModel(modelo);
            
            PreparedStatement ps;
            ResultSet rs;
            
            String sql_modelo = "SELECT modelotro.idmodelo,modelotro.numero"+
                    ",modelotro.color,modelotro.marca,modelotro.tipo"+
                    ",modelotro.clasificacion, modelotro.costo, almacen.existencia "
                    +"FROM modelotro,almacen WHERE almacen.id_modelo=modelotro.idmodelo";
            ps = con.prepareStatement(sql_modelo);
            rs = ps.executeQuery();
            ResultSetMetaData rSMd = rs.getMetaData();
            int cantidadcolumnas = rSMd.getColumnCount();
            modelo.addColumn("Modelo");
            modelo.addColumn("Numero");
            modelo.addColumn("Color");
            modelo.addColumn("Marca");
            modelo.addColumn("Tipo");
            modelo.addColumn("Clasificacion");
            modelo.addColumn("Costo");
            modelo.addColumn("Existencias");
            while(rs.next()){
                Object[] filas  = new Object[cantidadcolumnas];
                for (int i = 0; i < cantidadcolumnas; i++) {
                    filas[i] = rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        
        } catch (SQLException e) {
            System.out.println("Error: "+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentasIndex().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentasIndex.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegreso;
    private javax.swing.JButton btn_Comprar;
    private javax.swing.JSpinner cantidad_tt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_modelo;
    // End of variables declaration//GEN-END:variables

    public float getCosto() {
        return costo;
    }

    public void setCosto(float costo) {
        this.costo = costo;
    }

    public int getIdmodelo() {
        return idmodelo;
    }

    public void setIdmodelo(int idmodelo) {
        this.idmodelo = idmodelo;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getClasificacion() {
        return clasificacion;
    }

    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
}
